version: "3.8"

services:
  app:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
